---
- hosts: master
  become: true

  pre_tasks:
    - name: Load configuration.
      include_vars: config.yml

    - name: Ensure apt cache is up to date.
      apt:
        update_cache: true
        cache_valid_time: 3600

  handlers:
    - name: Include handlers.
      import_tasks: tasks/handlers.yml

  tasks:
    - name: Setup Docker.
      import_tasks: tasks/docker.yml

    - name: Set up Internet Monitoring.
      import_tasks: tasks/internet-monitoring.yml
      when: monitoring_enable

